use_frameworks!

platform :ios, '9.0'

target 'LKMacroCategoryModule_Example' do
  pod 'LKMacroCategoryModule', :path => '../'

  target 'LKMacroCategoryModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
